# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
	'exec-and-forget sketchybar',
	'exec-and-forget borders active_color=0xffff0000 inactive_color=0x00000000 width=10.0',
	'exec-and-forget ~/.config/aerospace-monitor/start-daemon.sh',
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

exec-on-workspace-change = [
	'/bin/bash',
	'-c',
	'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE; echo "$AEROSPACE_FOCUSED_WORKSPACE" > ~/.config/aerospace-monitor/workspace.state',
]
# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focus-changed = [
	'exec-and-forget sketchybar --trigger front_app_switched',
	'exec-and-forget sleep(0.1)',
	'move-mouse window-lazy-center',
	# 'exec-and-forget sketchybar --trigger send_message MESSAGE="Focus has changed"'
]

[workspace-to-monitor-force-assignment]
D = ['secondary', 'main']
O = ['secondary', 'main']
T = ['secondary', 'main']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = [{ monitor.main = 3 }, { monitor.secondary = 5 }, 3]
inner.vertical = [{ monitor.main = 3 }, { monitor.secondary = 5 }, 3]
outer.left = [{ monitor.main = 3 }, { monitor.secondary = 5 }, 3]
outer.bottom = [{ monitor.main = 3 }, { monitor.secondary = 5 }, 3]
outer.top = [{ monitor.main = 10 }, { monitor.secondary = 42 }, 10]
outer.right = [{ monitor.main = 3 }, { monitor.secondary = 5 }, 3]

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'focus-monitor --wrap-around next'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-node-to-monitor --wrap-around --focus-follows-window next'
alt-cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-period = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-f = "fullscreen"
# alt-f = 'exec-and-forget open -n /System/Library/CoreServices/Finder.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-ctrl-h = 'join-with left'
alt-ctrl-j = 'join-with down'
alt-ctrl-k = 'join-with up'
alt-ctrl-l = 'join-with right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-down = 'resize smart -50'
alt-up = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-a = 'workspace A' # In your config, you can drop workspace bindings that you don't need
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-d = 'workspace D'
alt-e = 'workspace E'
# alt-f = 'workspace F'
alt-g = 'workspace G'
# alt-i = 'workspace I'
alt-m = 'workspace M'
alt-n = 'workspace N'
alt-o = 'workspace O'
alt-p = 'workspace P'
alt-q = 'workspace Q'
alt-r = 'workspace R'
alt-s = 'workspace S'
alt-t = 'workspace T'
alt-u = 'workspace U'
alt-v = 'workspace V'
alt-w = 'workspace W'
alt-x = 'workspace X'
alt-y = 'workspace Y'
# alt-z = 'workspace Z'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-shift-a = ['move-node-to-workspace A', 'workspace A']
alt-shift-b = ['move-node-to-workspace B', 'workspace B']
alt-shift-c = ['move-node-to-workspace C', 'workspace C']
alt-shift-d = ['move-node-to-workspace D', 'workspace D']
alt-shift-e = ['move-node-to-workspace E', 'workspace E']
# alt-shift-f = 'move-node-to-workspace F', 'workspace F' ]
alt-shift-g = ['move-node-to-workspace G', 'workspace G']
# alt-shift-i = 'move-node-to-workspace I', 'workspace I' ]
alt-shift-m = ['move-node-to-workspace M', 'workspace M']
alt-shift-n = ['move-node-to-workspace N', 'workspace N']
alt-shift-o = ['move-node-to-workspace O', 'workspace O']
alt-shift-p = ['move-node-to-workspace P', 'workspace P']
alt-shift-q = ['move-node-to-workspace Q', 'workspace Q']
alt-shift-r = ['move-node-to-workspace R', 'workspace R']
alt-shift-s = ['move-node-to-workspace S', 'workspace S']
alt-shift-t = ['move-node-to-workspace T', 'workspace T']
alt-shift-u = ['move-node-to-workspace U', 'workspace U']
alt-shift-v = ['move-node-to-workspace V', 'workspace V']
alt-shift-w = ['move-node-to-workspace W', 'workspace W']
alt-shift-x = ['move-node-to-workspace X', 'workspace X']
alt-shift-y = ['move-node-to-workspace Y', 'workspace Y']
# alt-shift-z = 'move-node-to-workspace Z'

alt-ctrl-shift-1 = 'move-node-to-workspace 1'
alt-ctrl-shift-2 = 'move-node-to-workspace 2'
alt-ctrl-shift-3 = 'move-node-to-workspace 3'
alt-ctrl-shift-4 = 'move-node-to-workspace 4'
alt-ctrl-shift-5 = 'move-node-to-workspace 5'
alt-ctrl-shift-6 = 'move-node-to-workspace 6'
alt-ctrl-shift-7 = 'move-node-to-workspace 7'
alt-ctrl-shift-8 = 'move-node-to-workspace 8'
alt-ctrl-shift-9 = 'move-node-to-workspace 9'
alt-ctrl-shift-a = 'move-node-to-workspace A'
alt-ctrl-shift-b = 'move-node-to-workspace B'
alt-ctrl-shift-c = 'move-node-to-workspace C'
alt-ctrl-shift-d = 'move-node-to-workspace D'
alt-ctrl-shift-e = 'move-node-to-workspace E'
# alt-ctrl-shift-f = 'move-node-to-workspace F'
alt-ctrl-shift-g = 'move-node-to-workspace G'
# alt-ctrl-shift-i = 'move-node-to-workspace I'
alt-ctrl-shift-m = 'move-node-to-workspace M'
alt-ctrl-shift-n = 'move-node-to-workspace N'
alt-ctrl-shift-o = 'move-node-to-workspace O'
alt-ctrl-shift-p = 'move-node-to-workspace P'
alt-ctrl-shift-q = 'move-node-to-workspace Q'
alt-ctrl-shift-r = 'move-node-to-workspace R'
alt-ctrl-shift-s = 'move-node-to-workspace S'
alt-ctrl-shift-t = 'move-node-to-workspace T'
alt-ctrl-shift-u = 'move-node-to-workspace U'
alt-ctrl-shift-v = 'move-node-to-workspace V'
alt-ctrl-shift-w = 'move-node-to-workspace W'
alt-ctrl-shift-x = 'move-node-to-workspace X'
alt-ctrl-shift-y = 'move-node-to-workspace Y'
# alt-ctrl-shift-z = 'move-node-to-workspace Z'

# see: https://nikitabobko.github.io/aerospace/commands#mode
alt-shift-semicolon = [
	'mode service',
	'exec-and-forget sketchybar --set aerospace.mode icon="S" drawing=on',
]

# 'service' binding mode declaration.
# see: https://nikitabobko.github.io/aerospace/guide#binding-modes
[mode.service.binding]
esc = [
	'reload-config',
	'mode main',
	'exec-and-forget sketchybar --set aerospace.mode drawing=off',
]
r = [
	'flatten-workspace-tree',
	'mode main',
	'exec-and-forget sketchybar --set aerospace.mode drawing=off',
] # reset layout
f = [
	'layout floating tiling',
	'mode main',
	'exec-and-forget sketchybar --reload',
	'exec-and-forget borders active_color=0xffff0000 inactive_color=0x00000000 width=10.0',
	'exec-and-forget sleep 0.5 && sketchybar --trigger send_message message="aerospace reloaded"',
	'exec-and-forget sketchybar --set aerospace.mode drawing=off',
] # toggle between floating and tiling layout
backspace = [
	'close-all-windows-but-current',
	'mode main',
	'exec-and-forget sketchybar --set aerospace.mode drawing=off',
]

# sticky is not yet supported https://github.com/nikitabobko/aerospace/issues/2
#s = ['layout sticky tiling', 'mode main']

alt-shift-h = [
	'join-with left',
	'mode main',
	'exec-and-forget sketchybar --set aerospace.mode drawing=off',
]
alt-shift-j = [
	'join-with down',
	'mode main',
	'exec-and-forget sketchybar --set aerospace.mode drawing=off',
]
alt-shift-k = [
	'join-with up',
	'mode main',
	'exec-and-forget sketchybar --set aerospace.mode drawing=off',
]
alt-shift-l = [
	'join-with right',
	'mode main',
	'exec-and-forget sketchybar --set aerospace.mode drawing=off',
]

[[on-window-detected]]
if.app-id = 'company.thebrowser.browser'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = "move-node-to-workspace D"

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace M"

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = "move-node-to-workspace O"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace S"

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-name-regex-substring = 'system preferences'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'
